#!/usr/bin/env python
"""
Example node for using the nn_controller for a 6 DOF robot.

"""

import rospy
from nav_msgs.msg import Odometry
from neural_control.msg import PoseTwistStamped
from neural_control.nn_controller import NN_controller

def odom_callback(odom_msg):
	pose = odom_msg.pose.pose
	twist = odom_msg.pose.twist
	timestamp = odom_msg.header.stamp.to_sec()
	controller.give_new_state(pose, twist, timestamp)

def reference_callback(ref_msg):
	pose = ref_msg.pose
	twist = ref_msg.twist
	controller.give_new_reference(pose, twist)

controller = NN_controller(dof=6, kp=[100]*6, kd=[100]*6, kv=10, kw=10, N=10, sig='tanh', nn_limit=[10**10]*6)

rospy.init_node('controller')
rospy.Subscriber('/odom', Odometry, odom_callback)
rospy.Subscriber('/trajectory', PoseTwistStamped, reference_callback)

rospy.spin()
